services:
  backend:
    build:
      context: .
      dockerfile: ContainerFile
    container_name: backend
    volumes:
      - ./:/app
    ports:
      - 8080:8080
    expose:
      - 8080

  postgres:
    image: postgres:15
    container_name: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: fast-api
      POSTGRES_PASSWORD: fast-api
    ports:
      - 5432:5432

volumes:
  postgres-data:
